FROM nvcr.io/nvidia/tritonserver:24.10-trtllm-python-py3
WORKDIR /workspace
RUN pip install kaldialign soundfile tritonclient[grpc]==2.31
COPY build.sh .
COPY model_repo_whisper_qwen_trtllm model_repo_whisper_qwen_trtllm
COPY fill_template.py .




