services:
  asr:
    image: soar97/triton-whisper:24.05
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      - PYTHONIOENCODING=utf-8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: >
      /bin/bash -c "cd ./whisper_large_v3_trtllm_triton && bash ./build_whisper_fp16.sh && ln -sf ../../../whisper_large_v3/ model_repo_whisper_trtllm/whisper/1/ && bash launch_server.sh"
