# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "frame_reducer"
backend: "python"

max_batch_size: 512
input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims: [-1, -1 ]
  },
  {
    name: "x_lens"
    data_type: TYPE_INT64
    dims: [1]
    reshape: { shape: [ ] }
  }
]
output [
  {
    name: "out"
    data_type: TYPE_FP32
    dims: [-1, 384]
  },
  {
    name: "out_lens"
    data_type: TYPE_INT64
    dims: [1]
    reshape: { shape: [ ] }
  }

]

dynamic_batching {
  }

instance_group [
    {
      count: 2
      kind: KIND_GPU
    }
]
