var hierarchy =
[
    [ "sherpa_onnx::cxx::AudioEvent", "structsherpa__onnx_1_1cxx_1_1AudioEvent.html", null ],
    [ "sherpa_onnx::cxx::AudioTaggingConfig", "structsherpa__onnx_1_1cxx_1_1AudioTaggingConfig.html", null ],
    [ "sherpa_onnx::cxx::AudioTaggingModelConfig", "structsherpa__onnx_1_1cxx_1_1AudioTaggingModelConfig.html", null ],
    [ "sherpa_onnx::cxx::DenoisedAudio", "structsherpa__onnx_1_1cxx_1_1DenoisedAudio.html", null ],
    [ "sherpa_onnx::cxx::FeatureConfig", "structsherpa__onnx_1_1cxx_1_1FeatureConfig.html", null ],
    [ "sherpa_onnx::cxx::GeneratedAudio", "structsherpa__onnx_1_1cxx_1_1GeneratedAudio.html", null ],
    [ "sherpa_onnx::cxx::GenerationConfig", "structsherpa__onnx_1_1cxx_1_1GenerationConfig.html", null ],
    [ "sherpa_onnx::cxx::HomophoneReplacerConfig", "structsherpa__onnx_1_1cxx_1_1HomophoneReplacerConfig.html", null ],
    [ "sherpa_onnx::cxx::KeywordResult", "structsherpa__onnx_1_1cxx_1_1KeywordResult.html", null ],
    [ "sherpa_onnx::cxx::KeywordSpotterConfig", "structsherpa__onnx_1_1cxx_1_1KeywordSpotterConfig.html", null ],
    [ "sherpa_onnx::cxx::MoveOnly< Derived, T >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", null ],
    [ "sherpa_onnx::cxx::MoveOnly< AudioTagging, SherpaOnnxAudioTagging >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::AudioTagging", "classsherpa__onnx_1_1cxx_1_1AudioTagging.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< CircularBuffer, SherpaOnnxCircularBuffer >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::CircularBuffer", "classsherpa__onnx_1_1cxx_1_1CircularBuffer.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< KeywordSpotter, SherpaOnnxKeywordSpotter >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::KeywordSpotter", "classsherpa__onnx_1_1cxx_1_1KeywordSpotter.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< LinearResampler, SherpaOnnxLinearResampler >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::LinearResampler", "classsherpa__onnx_1_1cxx_1_1LinearResampler.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OfflinePunctuation, SherpaOnnxOfflinePunctuation >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OfflinePunctuation", "classsherpa__onnx_1_1cxx_1_1OfflinePunctuation.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OfflineRecognizer, SherpaOnnxOfflineRecognizer >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OfflineRecognizer", "classsherpa__onnx_1_1cxx_1_1OfflineRecognizer.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OfflineSourceSeparation, SherpaOnnxOfflineSourceSeparation >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OfflineSourceSeparation", "classsherpa__onnx_1_1cxx_1_1OfflineSourceSeparation.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OfflineSpeechDenoiser, SherpaOnnxOfflineSpeechDenoiser >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OfflineSpeechDenoiser", "classsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiser.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OfflineStream, SherpaOnnxOfflineStream >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OfflineStream", "classsherpa__onnx_1_1cxx_1_1OfflineStream.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OfflineTts, SherpaOnnxOfflineTts >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OfflineTts", "classsherpa__onnx_1_1cxx_1_1OfflineTts.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OnlinePunctuation, SherpaOnnxOnlinePunctuation >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OnlinePunctuation", "classsherpa__onnx_1_1cxx_1_1OnlinePunctuation.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OnlineRecognizer, SherpaOnnxOnlineRecognizer >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OnlineRecognizer", "classsherpa__onnx_1_1cxx_1_1OnlineRecognizer.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OnlineSpeechDenoiser, SherpaOnnxOnlineSpeechDenoiser >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OnlineSpeechDenoiser", "classsherpa__onnx_1_1cxx_1_1OnlineSpeechDenoiser.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< OnlineStream, SherpaOnnxOnlineStream >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::OnlineStream", "classsherpa__onnx_1_1cxx_1_1OnlineStream.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::MoveOnly< VoiceActivityDetector, SherpaOnnxVoiceActivityDetector >", "classsherpa__onnx_1_1cxx_1_1MoveOnly.html", [
      [ "sherpa_onnx::cxx::VoiceActivityDetector", "classsherpa__onnx_1_1cxx_1_1VoiceActivityDetector.html", null ]
    ] ],
    [ "sherpa_onnx::cxx::OfflineCanaryModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineCanaryModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineCohereTranscribeModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineCohereTranscribeModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineDolphinModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineDolphinModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineFireRedAsrCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineFireRedAsrCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineFireRedAsrModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineFireRedAsrModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineFunASRNanoModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineFunASRNanoModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineLMConfig", "structsherpa__onnx_1_1cxx_1_1OfflineLMConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineMedAsrCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineMedAsrCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineMoonshineModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineMoonshineModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineNemoEncDecCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineNemoEncDecCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineOmnilingualAsrCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineOmnilingualAsrCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineParaformerModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineParaformerModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflinePunctuationConfig", "structsherpa__onnx_1_1cxx_1_1OfflinePunctuationConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflinePunctuationModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflinePunctuationModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineQwen3ASRModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineQwen3ASRModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineRecognizerConfig", "structsherpa__onnx_1_1cxx_1_1OfflineRecognizerConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineRecognizerResult", "structsherpa__onnx_1_1cxx_1_1OfflineRecognizerResult.html", null ],
    [ "sherpa_onnx::cxx::OfflineSenseVoiceModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSenseVoiceModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSourceSeparationConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSourceSeparationModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSourceSeparationSpleeterModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationSpleeterModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSourceSeparationUvrModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationUvrModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSpeechDenoiserConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSpeechDenoiserDpdfNetModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserDpdfNetModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSpeechDenoiserGtcrnModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserGtcrnModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineSpeechDenoiserModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTdnnModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTdnnModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTransducerModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTransducerModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsKittenModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsKittenModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsKokoroModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsKokoroModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsMatchaModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsMatchaModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsPocketModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsPocketModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsSupertonicModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsSupertonicModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsVitsModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsVitsModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineTtsZipvoiceModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineTtsZipvoiceModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineWenetCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineWenetCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineWhisperModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineWhisperModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineZipformerAudioTaggingModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineZipformerAudioTaggingModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OfflineZipformerCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OfflineZipformerCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineCtcFstDecoderConfig", "structsherpa__onnx_1_1cxx_1_1OnlineCtcFstDecoderConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineModelConfig", "structsherpa__onnx_1_1cxx_1_1OnlineModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineNemoCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OnlineNemoCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineParaformerModelConfig", "structsherpa__onnx_1_1cxx_1_1OnlineParaformerModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlinePunctuationConfig", "structsherpa__onnx_1_1cxx_1_1OnlinePunctuationConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlinePunctuationModelConfig", "structsherpa__onnx_1_1cxx_1_1OnlinePunctuationModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineRecognizerConfig", "structsherpa__onnx_1_1cxx_1_1OnlineRecognizerConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineRecognizerResult", "structsherpa__onnx_1_1cxx_1_1OnlineRecognizerResult.html", null ],
    [ "sherpa_onnx::cxx::OnlineSpeechDenoiserConfig", "structsherpa__onnx_1_1cxx_1_1OnlineSpeechDenoiserConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineToneCtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OnlineToneCtcModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineTransducerModelConfig", "structsherpa__onnx_1_1cxx_1_1OnlineTransducerModelConfig.html", null ],
    [ "sherpa_onnx::cxx::OnlineZipformer2CtcModelConfig", "structsherpa__onnx_1_1cxx_1_1OnlineZipformer2CtcModelConfig.html", null ],
    [ "SherpaOnnxAudioEvent", "structSherpaOnnxAudioEvent.html", null ],
    [ "SherpaOnnxAudioTaggingConfig", "structSherpaOnnxAudioTaggingConfig.html", null ],
    [ "SherpaOnnxAudioTaggingModelConfig", "structSherpaOnnxAudioTaggingModelConfig.html", null ],
    [ "SherpaOnnxDenoisedAudio", "structSherpaOnnxDenoisedAudio.html", null ],
    [ "SherpaOnnxFastClusteringConfig", "structSherpaOnnxFastClusteringConfig.html", null ],
    [ "SherpaOnnxFeatureConfig", "structSherpaOnnxFeatureConfig.html", null ],
    [ "SherpaOnnxGeneratedAudio", "structSherpaOnnxGeneratedAudio.html", null ],
    [ "SherpaOnnxGenerationConfig", "structSherpaOnnxGenerationConfig.html", null ],
    [ "SherpaOnnxHomophoneReplacerConfig", "structSherpaOnnxHomophoneReplacerConfig.html", null ],
    [ "SherpaOnnxKeywordResult", "structSherpaOnnxKeywordResult.html", null ],
    [ "SherpaOnnxKeywordSpotterConfig", "structSherpaOnnxKeywordSpotterConfig.html", null ],
    [ "SherpaOnnxMultiChannelWave", "structSherpaOnnxMultiChannelWave.html", null ],
    [ "SherpaOnnxOfflineCanaryModelConfig", "structSherpaOnnxOfflineCanaryModelConfig.html", null ],
    [ "SherpaOnnxOfflineCohereTranscribeModelConfig", "structSherpaOnnxOfflineCohereTranscribeModelConfig.html", null ],
    [ "SherpaOnnxOfflineDolphinModelConfig", "structSherpaOnnxOfflineDolphinModelConfig.html", null ],
    [ "SherpaOnnxOfflineFireRedAsrCtcModelConfig", "structSherpaOnnxOfflineFireRedAsrCtcModelConfig.html", null ],
    [ "SherpaOnnxOfflineFireRedAsrModelConfig", "structSherpaOnnxOfflineFireRedAsrModelConfig.html", null ],
    [ "SherpaOnnxOfflineFunASRNanoModelConfig", "structSherpaOnnxOfflineFunASRNanoModelConfig.html", null ],
    [ "SherpaOnnxOfflineLMConfig", "structSherpaOnnxOfflineLMConfig.html", null ],
    [ "SherpaOnnxOfflineMedAsrCtcModelConfig", "structSherpaOnnxOfflineMedAsrCtcModelConfig.html", null ],
    [ "SherpaOnnxOfflineModelConfig", "structSherpaOnnxOfflineModelConfig.html", null ],
    [ "SherpaOnnxOfflineMoonshineModelConfig", "structSherpaOnnxOfflineMoonshineModelConfig.html", null ],
    [ "SherpaOnnxOfflineNemoEncDecCtcModelConfig", "structSherpaOnnxOfflineNemoEncDecCtcModelConfig.html", null ],
    [ "SherpaOnnxOfflineOmnilingualAsrCtcModelConfig", "structSherpaOnnxOfflineOmnilingualAsrCtcModelConfig.html", null ],
    [ "SherpaOnnxOfflineParaformerModelConfig", "structSherpaOnnxOfflineParaformerModelConfig.html", null ],
    [ "SherpaOnnxOfflinePunctuationConfig", "structSherpaOnnxOfflinePunctuationConfig.html", null ],
    [ "SherpaOnnxOfflinePunctuationModelConfig", "structSherpaOnnxOfflinePunctuationModelConfig.html", null ],
    [ "SherpaOnnxOfflineQwen3ASRModelConfig", "structSherpaOnnxOfflineQwen3ASRModelConfig.html", null ],
    [ "SherpaOnnxOfflineRecognizerConfig", "structSherpaOnnxOfflineRecognizerConfig.html", null ],
    [ "SherpaOnnxOfflineRecognizerResult", "structSherpaOnnxOfflineRecognizerResult.html", null ],
    [ "SherpaOnnxOfflineSenseVoiceModelConfig", "structSherpaOnnxOfflineSenseVoiceModelConfig.html", null ],
    [ "SherpaOnnxOfflineSourceSeparationConfig", "structSherpaOnnxOfflineSourceSeparationConfig.html", null ],
    [ "SherpaOnnxOfflineSourceSeparationModelConfig", "structSherpaOnnxOfflineSourceSeparationModelConfig.html", null ],
    [ "SherpaOnnxOfflineSourceSeparationSpleeterModelConfig", "structSherpaOnnxOfflineSourceSeparationSpleeterModelConfig.html", null ],
    [ "SherpaOnnxOfflineSourceSeparationUvrModelConfig", "structSherpaOnnxOfflineSourceSeparationUvrModelConfig.html", null ],
    [ "SherpaOnnxOfflineSpeakerDiarizationConfig", "structSherpaOnnxOfflineSpeakerDiarizationConfig.html", null ],
    [ "SherpaOnnxOfflineSpeakerDiarizationSegment", "structSherpaOnnxOfflineSpeakerDiarizationSegment.html", null ],
    [ "SherpaOnnxOfflineSpeakerSegmentationModelConfig", "structSherpaOnnxOfflineSpeakerSegmentationModelConfig.html", null ],
    [ "SherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig", "structSherpaOnnxOfflineSpeakerSegmentationPyannoteModelConfig.html", null ],
    [ "SherpaOnnxOfflineSpeechDenoiserConfig", "structSherpaOnnxOfflineSpeechDenoiserConfig.html", null ],
    [ "SherpaOnnxOfflineSpeechDenoiserDpdfNetModelConfig", "structSherpaOnnxOfflineSpeechDenoiserDpdfNetModelConfig.html", null ],
    [ "SherpaOnnxOfflineSpeechDenoiserGtcrnModelConfig", "structSherpaOnnxOfflineSpeechDenoiserGtcrnModelConfig.html", null ],
    [ "SherpaOnnxOfflineSpeechDenoiserModelConfig", "structSherpaOnnxOfflineSpeechDenoiserModelConfig.html", null ],
    [ "SherpaOnnxOfflineTdnnModelConfig", "structSherpaOnnxOfflineTdnnModelConfig.html", null ],
    [ "SherpaOnnxOfflineTransducerModelConfig", "structSherpaOnnxOfflineTransducerModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsConfig", "structSherpaOnnxOfflineTtsConfig.html", null ],
    [ "SherpaOnnxOfflineTtsKittenModelConfig", "structSherpaOnnxOfflineTtsKittenModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsKokoroModelConfig", "structSherpaOnnxOfflineTtsKokoroModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsMatchaModelConfig", "structSherpaOnnxOfflineTtsMatchaModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsModelConfig", "structSherpaOnnxOfflineTtsModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsPocketModelConfig", "structSherpaOnnxOfflineTtsPocketModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsSupertonicModelConfig", "structSherpaOnnxOfflineTtsSupertonicModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsVitsModelConfig", "structSherpaOnnxOfflineTtsVitsModelConfig.html", null ],
    [ "SherpaOnnxOfflineTtsZipvoiceModelConfig", "structSherpaOnnxOfflineTtsZipvoiceModelConfig.html", null ],
    [ "SherpaOnnxOfflineWenetCtcModelConfig", "structSherpaOnnxOfflineWenetCtcModelConfig.html", null ],
    [ "SherpaOnnxOfflineWhisperModelConfig", "structSherpaOnnxOfflineWhisperModelConfig.html", null ],
    [ "SherpaOnnxOfflineZipformerAudioTaggingModelConfig", "structSherpaOnnxOfflineZipformerAudioTaggingModelConfig.html", null ],
    [ "SherpaOnnxOfflineZipformerCtcModelConfig", "structSherpaOnnxOfflineZipformerCtcModelConfig.html", null ],
    [ "SherpaOnnxOnlineCtcFstDecoderConfig", "structSherpaOnnxOnlineCtcFstDecoderConfig.html", null ],
    [ "SherpaOnnxOnlineModelConfig", "structSherpaOnnxOnlineModelConfig.html", null ],
    [ "SherpaOnnxOnlineNemoCtcModelConfig", "structSherpaOnnxOnlineNemoCtcModelConfig.html", null ],
    [ "SherpaOnnxOnlineParaformerModelConfig", "structSherpaOnnxOnlineParaformerModelConfig.html", null ],
    [ "SherpaOnnxOnlinePunctuationConfig", "structSherpaOnnxOnlinePunctuationConfig.html", null ],
    [ "SherpaOnnxOnlinePunctuationModelConfig", "structSherpaOnnxOnlinePunctuationModelConfig.html", null ],
    [ "SherpaOnnxOnlineRecognizerConfig", "structSherpaOnnxOnlineRecognizerConfig.html", null ],
    [ "SherpaOnnxOnlineRecognizerResult", "structSherpaOnnxOnlineRecognizerResult.html", null ],
    [ "SherpaOnnxOnlineSpeechDenoiserConfig", "structSherpaOnnxOnlineSpeechDenoiserConfig.html", null ],
    [ "SherpaOnnxOnlineToneCtcModelConfig", "structSherpaOnnxOnlineToneCtcModelConfig.html", null ],
    [ "SherpaOnnxOnlineTransducerModelConfig", "structSherpaOnnxOnlineTransducerModelConfig.html", null ],
    [ "SherpaOnnxOnlineZipformer2CtcModelConfig", "structSherpaOnnxOnlineZipformer2CtcModelConfig.html", null ],
    [ "SherpaOnnxResampleOut", "structSherpaOnnxResampleOut.html", null ],
    [ "SherpaOnnxSileroVadModelConfig", "structSherpaOnnxSileroVadModelConfig.html", null ],
    [ "SherpaOnnxSourceSeparationOutput", "structSherpaOnnxSourceSeparationOutput.html", null ],
    [ "SherpaOnnxSourceSeparationStem", "structSherpaOnnxSourceSeparationStem.html", null ],
    [ "SherpaOnnxSpeakerEmbeddingExtractorConfig", "structSherpaOnnxSpeakerEmbeddingExtractorConfig.html", null ],
    [ "SherpaOnnxSpeakerEmbeddingManagerBestMatchesResult", "structSherpaOnnxSpeakerEmbeddingManagerBestMatchesResult.html", null ],
    [ "SherpaOnnxSpeakerEmbeddingManagerSpeakerMatch", "structSherpaOnnxSpeakerEmbeddingManagerSpeakerMatch.html", null ],
    [ "SherpaOnnxSpeechSegment", "structSherpaOnnxSpeechSegment.html", null ],
    [ "SherpaOnnxSpokenLanguageIdentificationConfig", "structSherpaOnnxSpokenLanguageIdentificationConfig.html", null ],
    [ "SherpaOnnxSpokenLanguageIdentificationResult", "structSherpaOnnxSpokenLanguageIdentificationResult.html", null ],
    [ "SherpaOnnxSpokenLanguageIdentificationWhisperConfig", "structSherpaOnnxSpokenLanguageIdentificationWhisperConfig.html", null ],
    [ "SherpaOnnxTenVadModelConfig", "structSherpaOnnxTenVadModelConfig.html", null ],
    [ "SherpaOnnxVadModelConfig", "structSherpaOnnxVadModelConfig.html", null ],
    [ "SherpaOnnxWave", "structSherpaOnnxWave.html", null ],
    [ "sherpa_onnx::cxx::SileroVadModelConfig", "structsherpa__onnx_1_1cxx_1_1SileroVadModelConfig.html", null ],
    [ "sherpa_onnx::cxx::SourceSeparationOutput", "structsherpa__onnx_1_1cxx_1_1SourceSeparationOutput.html", null ],
    [ "sherpa_onnx::cxx::SourceSeparationStem", "structsherpa__onnx_1_1cxx_1_1SourceSeparationStem.html", null ],
    [ "sherpa_onnx::cxx::SpeechSegment", "structsherpa__onnx_1_1cxx_1_1SpeechSegment.html", null ],
    [ "sherpa_onnx::cxx::TenVadModelConfig", "structsherpa__onnx_1_1cxx_1_1TenVadModelConfig.html", null ],
    [ "sherpa_onnx::cxx::VadModelConfig", "structsherpa__onnx_1_1cxx_1_1VadModelConfig.html", null ],
    [ "sherpa_onnx::cxx::Wave", "structsherpa__onnx_1_1cxx_1_1Wave.html", null ]
];