FROM  nvcr.io/nvidia/tritonserver:22.08-py3-sdk
# https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
# Please choose previous tritonserver:xx.xx if you encounter cuda driver mismatch issue

LABEL maintainer="NVIDIA"
LABEL repository="tritonserver"

RUN apt-get update && apt-get install -y libsndfile1
RUN pip3 install soundfile
RUN pip3 install kaldialign

WORKDIR /workspace
