var searchData=
[
  ['offline_20asr_20models_0',['Non-Streaming (Offline) ASR Models',['../offline_asr.html',1,'']]],
  ['offline_20dpdfnet_1',['Offline DPDFNet',['../speech_enhancement.html#se_offline_dpdfnet',1,'']]],
  ['offline_20gtcrn_2',['Offline GTCRN',['../speech_enhancement.html#se_offline_gtcrn',1,'']]],
  ['offline_20punctuation_3',['Offline Punctuation',['../punctuation.html#punct_offline',1,'']]],
  ['offline_20speaker_20diarization_4',['Offline Speaker Diarization',['../speaker_diarization.html',1,'']]],
  ['offline_2dasr_2edox_5',['offline-asr.dox',['../offline-asr_8dox.html',1,'']]],
  ['offlinecanarymodelconfig_6',['OfflineCanaryModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineCanaryModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinecoheretranscribemodelconfig_7',['OfflineCohereTranscribeModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineCohereTranscribeModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinectcfstdecoderconfig_8',['OfflineCtcFstDecoderConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineCtcFstDecoderConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinediacritization_9',['OfflineDiacritization',['../classsherpa__onnx_1_1cxx_1_1OfflineDiacritization.html',1,'sherpa_onnx::cxx']]],
  ['offlinediacritizationconfig_10',['OfflineDiacritizationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineDiacritizationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinediacritizationmodelconfig_11',['OfflineDiacritizationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineDiacritizationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinedolphinmodelconfig_12',['OfflineDolphinModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineDolphinModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinefireredasrctcmodelconfig_13',['OfflineFireRedAsrCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineFireRedAsrCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinefireredasrmodelconfig_14',['OfflineFireRedAsrModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineFireRedAsrModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinefunasrnanomodelconfig_15',['OfflineFunASRNanoModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineFunASRNanoModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinelmconfig_16',['OfflineLMConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineLMConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinemedasrctcmodelconfig_17',['OfflineMedAsrCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineMedAsrCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinemodelconfig_18',['OfflineModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinemoonshinemodelconfig_19',['OfflineMoonshineModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineMoonshineModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinenemoencdecctcmodelconfig_20',['OfflineNemoEncDecCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineNemoEncDecCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlineomnilingualasrctcmodelconfig_21',['OfflineOmnilingualAsrCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineOmnilingualAsrCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlineparaformermodelconfig_22',['OfflineParaformerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineParaformerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinepunctuation_23',['OfflinePunctuation',['../classsherpa__onnx_1_1cxx_1_1OfflinePunctuation.html',1,'sherpa_onnx::cxx']]],
  ['offlinepunctuationconfig_24',['OfflinePunctuationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflinePunctuationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinepunctuationmodelconfig_25',['OfflinePunctuationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflinePunctuationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlineqwen3asrmodelconfig_26',['OfflineQwen3ASRModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineQwen3ASRModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinerecognizer_27',['OfflineRecognizer',['../classsherpa__onnx_1_1cxx_1_1OfflineRecognizer.html',1,'sherpa_onnx::cxx']]],
  ['offlinerecognizerconfig_28',['OfflineRecognizerConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineRecognizerConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinerecognizerresult_29',['OfflineRecognizerResult',['../structsherpa__onnx_1_1cxx_1_1OfflineRecognizerResult.html',1,'sherpa_onnx::cxx']]],
  ['offlinesensevoicemodelconfig_30',['OfflineSenseVoiceModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSenseVoiceModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparation_31',['OfflineSourceSeparation',['../classsherpa__onnx_1_1cxx_1_1OfflineSourceSeparation.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationconfig_32',['OfflineSourceSeparationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationmodelconfig_33',['OfflineSourceSeparationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationspleetermodelconfig_34',['OfflineSourceSeparationSpleeterModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationSpleeterModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationuvrmodelconfig_35',['OfflineSourceSeparationUvrModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationUvrModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarization_36',['OfflineSpeakerDiarization',['../classsherpa__onnx_1_1cxx_1_1OfflineSpeakerDiarization.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarizationconfig_37',['OfflineSpeakerDiarizationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerDiarizationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarizationprogresscallback_38',['OfflineSpeakerDiarizationProgressCallback',['../namespacesherpa__onnx_1_1cxx.html#ac9943bfd30350f2a70514f0f2a63cec6',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarizationsegment_39',['OfflineSpeakerDiarizationSegment',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerDiarizationSegment.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakersegmentationmodelconfig_40',['OfflineSpeakerSegmentationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerSegmentationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakersegmentationpyannotemodelconfig_41',['OfflineSpeakerSegmentationPyannoteModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerSegmentationPyannoteModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoiser_42',['OfflineSpeechDenoiser',['../classsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiser.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoiserconfig_43',['OfflineSpeechDenoiserConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoiserdpdfnetmodelconfig_44',['OfflineSpeechDenoiserDpdfNetModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserDpdfNetModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoisergtcrnmodelconfig_45',['OfflineSpeechDenoiserGtcrnModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserGtcrnModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoisermodelconfig_46',['OfflineSpeechDenoiserModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinestream_47',['offlinestream',['../classsherpa__onnx_1_1cxx_1_1OfflineStream.html#add7ecce32d22317d39018c3905951ba4',1,'sherpa_onnx::cxx::OfflineStream::OfflineStream()'],['../classsherpa__onnx_1_1cxx_1_1OfflineStream.html',1,'sherpa_onnx::cxx::OfflineStream']]],
  ['offlinetdnnmodelconfig_48',['OfflineTdnnModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTdnnModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinetransducermodelconfig_49',['OfflineTransducerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTransducerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinetts_50',['OfflineTts',['../classsherpa__onnx_1_1cxx_1_1OfflineTts.html',1,'sherpa_onnx::cxx']]],
  ['offlinettscallback_51',['OfflineTtsCallback',['../namespacesherpa__onnx_1_1cxx.html#a0f48ba20dba546f608d49a75f9fffe1e',1,'sherpa_onnx::cxx']]],
  ['offlinettsconfig_52',['OfflineTtsConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettskittenmodelconfig_53',['OfflineTtsKittenModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsKittenModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettskokoromodelconfig_54',['OfflineTtsKokoroModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsKokoroModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettsmatchamodelconfig_55',['OfflineTtsMatchaModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsMatchaModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettsmodelconfig_56',['OfflineTtsModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettspocketmodelconfig_57',['OfflineTtsPocketModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsPocketModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettssupertonicmodelconfig_58',['OfflineTtsSupertonicModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsSupertonicModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettsvitsmodelconfig_59',['OfflineTtsVitsModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsVitsModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettszipvoicemodelconfig_60',['OfflineTtsZipvoiceModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsZipvoiceModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinewenetctcmodelconfig_61',['OfflineWenetCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineWenetCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinewhispermodelconfig_62',['OfflineWhisperModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineWhisperModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinezipformeraudiotaggingmodelconfig_63',['OfflineZipformerAudioTaggingModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineZipformerAudioTaggingModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinezipformerctcmodelconfig_64',['OfflineZipformerCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineZipformerCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['omnilingual_65',['omnilingual',['../offline_asr.html#offline_asr_omnilingual',1,'Omnilingual'],['../structsherpa__onnx_1_1cxx_1_1OfflineModelConfig.html#aef5b6e6419e07d8868856f9dc57ed939',1,'sherpa_onnx::cxx::OfflineModelConfig::omnilingual'],['../structSherpaOnnxOfflineModelConfig.html#a42baf10961f58bbbe6fc5ca7b98f6be7',1,'SherpaOnnxOfflineModelConfig::omnilingual']]],
  ['one_20ctc_66',['T-One CTC',['../online_asr.html#online_asr_t_one',1,'']]],
  ['online_20asr_20models_67',['Streaming (Online) ASR Models',['../online_asr.html',1,'']]],
  ['online_20dpdfnet_68',['Online DPDFNet',['../speech_enhancement.html#se_online_dpdfnet',1,'']]],
  ['online_20gtcrn_69',['Online GTCRN',['../speech_enhancement.html#se_online_gtcrn',1,'']]],
  ['online_20punctuation_70',['Online Punctuation',['../punctuation.html#punct_online',1,'']]],
  ['online_2dasr_2edox_71',['online-asr.dox',['../online-asr_8dox.html',1,'']]],
  ['onlinectcfstdecoderconfig_72',['OnlineCtcFstDecoderConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineCtcFstDecoderConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinemodelconfig_73',['OnlineModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinenemoctcmodelconfig_74',['OnlineNemoCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineNemoCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlineparaformermodelconfig_75',['OnlineParaformerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineParaformerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinepunctuation_76',['OnlinePunctuation',['../classsherpa__onnx_1_1cxx_1_1OnlinePunctuation.html',1,'sherpa_onnx::cxx']]],
  ['onlinepunctuationconfig_77',['OnlinePunctuationConfig',['../structsherpa__onnx_1_1cxx_1_1OnlinePunctuationConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinepunctuationmodelconfig_78',['OnlinePunctuationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlinePunctuationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinerecognizer_79',['OnlineRecognizer',['../classsherpa__onnx_1_1cxx_1_1OnlineRecognizer.html',1,'sherpa_onnx::cxx']]],
  ['onlinerecognizerconfig_80',['OnlineRecognizerConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineRecognizerConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinerecognizerresult_81',['OnlineRecognizerResult',['../structsherpa__onnx_1_1cxx_1_1OnlineRecognizerResult.html',1,'sherpa_onnx::cxx']]],
  ['onlinespeechdenoiser_82',['OnlineSpeechDenoiser',['../classsherpa__onnx_1_1cxx_1_1OnlineSpeechDenoiser.html',1,'sherpa_onnx::cxx']]],
  ['onlinespeechdenoiserconfig_83',['OnlineSpeechDenoiserConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineSpeechDenoiserConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinestream_84',['onlinestream',['../classsherpa__onnx_1_1cxx_1_1OnlineStream.html#a82a4b0a48433a7584e8a0150ec1d1e95',1,'sherpa_onnx::cxx::OnlineStream::OnlineStream()'],['../classsherpa__onnx_1_1cxx_1_1OnlineStream.html',1,'sherpa_onnx::cxx::OnlineStream']]],
  ['onlinetonectcmodelconfig_85',['OnlineToneCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineToneCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinetransducermodelconfig_86',['OnlineTransducerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineTransducerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinezipformer2ctcmodelconfig_87',['OnlineZipformer2CtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineZipformer2CtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onnx_20public_20api_20documentation_88',['sherpa-onnx public API documentation',['../index.html',1,'']]],
  ['operator_3d_89',['operator=',['../classsherpa__onnx_1_1cxx_1_1MoveOnly.html#a9c1d3e8fe380f3692f42bf83c3c22ef7',1,'sherpa_onnx::cxx::MoveOnly::operator=(MoveOnly &amp;&amp;other)'],['../classsherpa__onnx_1_1cxx_1_1MoveOnly.html#a87ab6546086729291774cc3b44f09657',1,'sherpa_onnx::cxx::MoveOnly::operator=(const MoveOnly &amp;)=delete']]],
  ['ownership_20rules_90',['Common ownership rules',['../index.html#autotoc_md4',1,'']]]
];
