var searchData=
[
  ['offline_20asr_20models_0',['Non-Streaming (Offline) ASR Models',['../offline_asr.html',1,'']]],
  ['offline_20dpdfnet_1',['Offline DPDFNet',['../speech_enhancement.html#se_offline_dpdfnet',1,'']]],
  ['offline_20gtcrn_2',['Offline GTCRN',['../speech_enhancement.html#se_offline_gtcrn',1,'']]],
  ['offline_20punctuation_3',['Offline Punctuation',['../punctuation.html#punct_offline',1,'']]],
  ['offline_20speaker_20diarization_4',['Offline Speaker Diarization',['../speaker_diarization.html',1,'']]],
  ['offline_2dasr_2edox_5',['offline-asr.dox',['../offline-asr_8dox.html',1,'']]],
  ['offlinecanarymodelconfig_6',['OfflineCanaryModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineCanaryModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinecoheretranscribemodelconfig_7',['OfflineCohereTranscribeModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineCohereTranscribeModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinediacritization_8',['OfflineDiacritization',['../classsherpa__onnx_1_1cxx_1_1OfflineDiacritization.html',1,'sherpa_onnx::cxx']]],
  ['offlinediacritizationconfig_9',['OfflineDiacritizationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineDiacritizationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinediacritizationmodelconfig_10',['OfflineDiacritizationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineDiacritizationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinedolphinmodelconfig_11',['OfflineDolphinModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineDolphinModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinefireredasrctcmodelconfig_12',['OfflineFireRedAsrCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineFireRedAsrCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinefireredasrmodelconfig_13',['OfflineFireRedAsrModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineFireRedAsrModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinefunasrnanomodelconfig_14',['OfflineFunASRNanoModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineFunASRNanoModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinelmconfig_15',['OfflineLMConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineLMConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinemedasrctcmodelconfig_16',['OfflineMedAsrCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineMedAsrCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinemodelconfig_17',['OfflineModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinemoonshinemodelconfig_18',['OfflineMoonshineModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineMoonshineModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinenemoencdecctcmodelconfig_19',['OfflineNemoEncDecCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineNemoEncDecCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlineomnilingualasrctcmodelconfig_20',['OfflineOmnilingualAsrCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineOmnilingualAsrCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlineparaformermodelconfig_21',['OfflineParaformerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineParaformerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinepunctuation_22',['OfflinePunctuation',['../classsherpa__onnx_1_1cxx_1_1OfflinePunctuation.html',1,'sherpa_onnx::cxx']]],
  ['offlinepunctuationconfig_23',['OfflinePunctuationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflinePunctuationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinepunctuationmodelconfig_24',['OfflinePunctuationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflinePunctuationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlineqwen3asrmodelconfig_25',['OfflineQwen3ASRModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineQwen3ASRModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinerecognizer_26',['OfflineRecognizer',['../classsherpa__onnx_1_1cxx_1_1OfflineRecognizer.html',1,'sherpa_onnx::cxx']]],
  ['offlinerecognizerconfig_27',['OfflineRecognizerConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineRecognizerConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinerecognizerresult_28',['OfflineRecognizerResult',['../structsherpa__onnx_1_1cxx_1_1OfflineRecognizerResult.html',1,'sherpa_onnx::cxx']]],
  ['offlinesensevoicemodelconfig_29',['OfflineSenseVoiceModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSenseVoiceModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparation_30',['OfflineSourceSeparation',['../classsherpa__onnx_1_1cxx_1_1OfflineSourceSeparation.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationconfig_31',['OfflineSourceSeparationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationmodelconfig_32',['OfflineSourceSeparationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationspleetermodelconfig_33',['OfflineSourceSeparationSpleeterModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationSpleeterModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinesourceseparationuvrmodelconfig_34',['OfflineSourceSeparationUvrModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSourceSeparationUvrModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarization_35',['OfflineSpeakerDiarization',['../classsherpa__onnx_1_1cxx_1_1OfflineSpeakerDiarization.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarizationconfig_36',['OfflineSpeakerDiarizationConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerDiarizationConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarizationprogresscallback_37',['OfflineSpeakerDiarizationProgressCallback',['../namespacesherpa__onnx_1_1cxx.html#ac9943bfd30350f2a70514f0f2a63cec6',1,'sherpa_onnx::cxx']]],
  ['offlinespeakerdiarizationsegment_38',['OfflineSpeakerDiarizationSegment',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerDiarizationSegment.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakersegmentationmodelconfig_39',['OfflineSpeakerSegmentationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerSegmentationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeakersegmentationpyannotemodelconfig_40',['OfflineSpeakerSegmentationPyannoteModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeakerSegmentationPyannoteModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoiser_41',['OfflineSpeechDenoiser',['../classsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiser.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoiserconfig_42',['OfflineSpeechDenoiserConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoiserdpdfnetmodelconfig_43',['OfflineSpeechDenoiserDpdfNetModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserDpdfNetModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoisergtcrnmodelconfig_44',['OfflineSpeechDenoiserGtcrnModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserGtcrnModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinespeechdenoisermodelconfig_45',['OfflineSpeechDenoiserModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineSpeechDenoiserModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinestream_46',['offlinestream',['../classsherpa__onnx_1_1cxx_1_1OfflineStream.html#add7ecce32d22317d39018c3905951ba4',1,'sherpa_onnx::cxx::OfflineStream::OfflineStream()'],['../classsherpa__onnx_1_1cxx_1_1OfflineStream.html',1,'sherpa_onnx::cxx::OfflineStream']]],
  ['offlinetdnnmodelconfig_47',['OfflineTdnnModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTdnnModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinetransducermodelconfig_48',['OfflineTransducerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTransducerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinetts_49',['OfflineTts',['../classsherpa__onnx_1_1cxx_1_1OfflineTts.html',1,'sherpa_onnx::cxx']]],
  ['offlinettscallback_50',['OfflineTtsCallback',['../namespacesherpa__onnx_1_1cxx.html#a0f48ba20dba546f608d49a75f9fffe1e',1,'sherpa_onnx::cxx']]],
  ['offlinettsconfig_51',['OfflineTtsConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettskittenmodelconfig_52',['OfflineTtsKittenModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsKittenModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettskokoromodelconfig_53',['OfflineTtsKokoroModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsKokoroModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettsmatchamodelconfig_54',['OfflineTtsMatchaModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsMatchaModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettsmodelconfig_55',['OfflineTtsModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettspocketmodelconfig_56',['OfflineTtsPocketModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsPocketModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettssupertonicmodelconfig_57',['OfflineTtsSupertonicModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsSupertonicModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettsvitsmodelconfig_58',['OfflineTtsVitsModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsVitsModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinettszipvoicemodelconfig_59',['OfflineTtsZipvoiceModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineTtsZipvoiceModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinewenetctcmodelconfig_60',['OfflineWenetCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineWenetCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinewhispermodelconfig_61',['OfflineWhisperModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineWhisperModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinezipformeraudiotaggingmodelconfig_62',['OfflineZipformerAudioTaggingModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineZipformerAudioTaggingModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['offlinezipformerctcmodelconfig_63',['OfflineZipformerCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OfflineZipformerCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['omnilingual_64',['omnilingual',['../offline_asr.html#offline_asr_omnilingual',1,'Omnilingual'],['../structsherpa__onnx_1_1cxx_1_1OfflineModelConfig.html#aef5b6e6419e07d8868856f9dc57ed939',1,'sherpa_onnx::cxx::OfflineModelConfig::omnilingual'],['../structSherpaOnnxOfflineModelConfig.html#a42baf10961f58bbbe6fc5ca7b98f6be7',1,'SherpaOnnxOfflineModelConfig::omnilingual']]],
  ['one_20ctc_65',['T-One CTC',['../online_asr.html#online_asr_t_one',1,'']]],
  ['online_20asr_20models_66',['Streaming (Online) ASR Models',['../online_asr.html',1,'']]],
  ['online_20dpdfnet_67',['Online DPDFNet',['../speech_enhancement.html#se_online_dpdfnet',1,'']]],
  ['online_20gtcrn_68',['Online GTCRN',['../speech_enhancement.html#se_online_gtcrn',1,'']]],
  ['online_20punctuation_69',['Online Punctuation',['../punctuation.html#punct_online',1,'']]],
  ['online_2dasr_2edox_70',['online-asr.dox',['../online-asr_8dox.html',1,'']]],
  ['onlinectcfstdecoderconfig_71',['OnlineCtcFstDecoderConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineCtcFstDecoderConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinemodelconfig_72',['OnlineModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinenemoctcmodelconfig_73',['OnlineNemoCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineNemoCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlineparaformermodelconfig_74',['OnlineParaformerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineParaformerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinepunctuation_75',['OnlinePunctuation',['../classsherpa__onnx_1_1cxx_1_1OnlinePunctuation.html',1,'sherpa_onnx::cxx']]],
  ['onlinepunctuationconfig_76',['OnlinePunctuationConfig',['../structsherpa__onnx_1_1cxx_1_1OnlinePunctuationConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinepunctuationmodelconfig_77',['OnlinePunctuationModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlinePunctuationModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinerecognizer_78',['OnlineRecognizer',['../classsherpa__onnx_1_1cxx_1_1OnlineRecognizer.html',1,'sherpa_onnx::cxx']]],
  ['onlinerecognizerconfig_79',['OnlineRecognizerConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineRecognizerConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinerecognizerresult_80',['OnlineRecognizerResult',['../structsherpa__onnx_1_1cxx_1_1OnlineRecognizerResult.html',1,'sherpa_onnx::cxx']]],
  ['onlinespeechdenoiser_81',['OnlineSpeechDenoiser',['../classsherpa__onnx_1_1cxx_1_1OnlineSpeechDenoiser.html',1,'sherpa_onnx::cxx']]],
  ['onlinespeechdenoiserconfig_82',['OnlineSpeechDenoiserConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineSpeechDenoiserConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinestream_83',['onlinestream',['../classsherpa__onnx_1_1cxx_1_1OnlineStream.html#a82a4b0a48433a7584e8a0150ec1d1e95',1,'sherpa_onnx::cxx::OnlineStream::OnlineStream()'],['../classsherpa__onnx_1_1cxx_1_1OnlineStream.html',1,'sherpa_onnx::cxx::OnlineStream']]],
  ['onlinetonectcmodelconfig_84',['OnlineToneCtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineToneCtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinetransducermodelconfig_85',['OnlineTransducerModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineTransducerModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onlinezipformer2ctcmodelconfig_86',['OnlineZipformer2CtcModelConfig',['../structsherpa__onnx_1_1cxx_1_1OnlineZipformer2CtcModelConfig.html',1,'sherpa_onnx::cxx']]],
  ['onnx_20public_20api_20documentation_87',['sherpa-onnx public API documentation',['../index.html',1,'']]],
  ['operator_3d_88',['operator=',['../classsherpa__onnx_1_1cxx_1_1MoveOnly.html#a9c1d3e8fe380f3692f42bf83c3c22ef7',1,'sherpa_onnx::cxx::MoveOnly::operator=(MoveOnly &amp;&amp;other)'],['../classsherpa__onnx_1_1cxx_1_1MoveOnly.html#a87ab6546086729291774cc3b44f09657',1,'sherpa_onnx::cxx::MoveOnly::operator=(const MoveOnly &amp;)=delete']]],
  ['ownership_20rules_89',['Common ownership rules',['../index.html#autotoc_md4',1,'']]]
];
