name: build_conda_cpu

on:
  push:
    tags:
      - '*'

jobs:
  generate_build_matrix:
    # see https://github.com/pytorch/pytorch/pull/50633
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          # outputting for debugging purposes
          python scripts/github_actions/generate_build_matrix.py
          MATRIX=$(python scripts/github_actions/generate_build_matrix.py)
          echo "::set-output name=matrix::${MATRIX}"

  build_conda_cpu:
    needs: generate_build_matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      # refer to https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: sherpa

      - name: Install conda dependencies
        shell: bash -l {0}
        run: |
          conda install -y -q anaconda-client
          conda install -y -q conda-build
          conda install -y -q -c k2-fsa -c kaldifeat -c pytorch k2 kaldifeat pytorch=${{ matrix.torch }} cpuonly

      - name: Display MKL
        if: startsWith(matrix.os, 'macos') || startsWith(matrix.os, 'ubuntu')
        shell: bash -l {0}
        run: |
          ls -lh $CONDA_PREFIX/lib/libmkl*

      - name: Display Python version
        shell: bash -l {0}
        run: |
          python -c "import sys; print(sys.version)"
          which python

      - name: Display conda info
        shell: bash -l {0}
        run: |
          conda env list
          conda info
          which conda
          python --version
          which python
          python -m torch.utils.collect_env

      - name: Build sherpa
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
        shell: bash -l {0}
        env:
          SHERPA_PYTHON_VERSION: ${{ matrix.python-version}}
          SHERPA_TORCH_VERSION: ${{ matrix.torch }}
          SHERPA_CONDA_TOKEN: ${{ secrets.SHERPA_CONDA_TOKEN}}
        run: |
          ./scripts/build_conda_cpu.sh

      - name: Build sherpa
        if: startsWith(matrix.os, 'windows')
        shell: bash -l {0}
        env:
          SHERPA_PYTHON_VERSION: ${{ matrix.python-version}}
          SHERPA_TORCH_VERSION: ${{ matrix.torch }}
          SHERPA_CONDA_TOKEN: ${{ secrets.SHERPA_CONDA_TOKEN}}
        run: |
          # ./scripts/build_conda_cpu_windows.sh
          ./scripts/build_conda_cpu.sh

      - name: Display generated files
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          ls -lh /usr/share/miniconda/envs/sherpa/conda-bld/linux-64

      - name: Upload generated files
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          name: cpu-torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: /usr/share/miniconda/envs/sherpa/conda-bld/linux-64/*.tar.bz2

      - name: Display generated files
        if: startsWith(matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          ls -lh /c/Miniconda/envs/sherpa/conda-bld
          ls -lh /c/Miniconda/envs/sherpa/conda-bld/*/*
          ls -lh /c/Miniconda/envs/sherpa/conda-bld/win-64/*

      - name: Upload generated files
        if: startsWith(matrix.os, 'windows')
        uses: actions/upload-artifact@v2
        with:
          name: cpu-torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: c:/Miniconda/envs/sherpa/conda-bld/win-64/*.tar.bz2

      - name: Display generated files
        if: startsWith(matrix.os, 'macos')
        run: |
          ls -lh /usr/local/miniconda/envs/sherpa/conda-bld/osx-64

      - name: Upload generated files
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@v2
        with:
          name: cpu-torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-${{ matrix.os }}
          path: /usr/local/miniconda/envs/sherpa/conda-bld/osx-64/*.tar.bz2
