name: build-wheels-cpu-macos

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: build-wheels-cpu-macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_build_matrix:
    # see https://github.com/pytorch/pytorch/pull/50633
    runs-on: macos-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generating build matrix
        id: set-matrix
        run: |
          # outputting for debugging purposes
          python ./scripts/github_actions/generate_build_matrix.py --for-macos
          MATRIX=$(python ./scripts/github_actions/generate_build_matrix.py --for-macos)
          echo "::set-output name=matrix::${MATRIX}"

  build_wheels_macos_cpu:
    needs: generate_build_matrix
    name: ${{ matrix.torch }} ${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ${{ fromJson(needs.generate_build_matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # see https://cibuildwheel.readthedocs.io/en/stable/changelog/
      # for a list of versions
      - name: Build wheels
        shell: bash
        run:
          pip install -U pip
          pip install cmake numpy setuptools wheel

          pip install torch==${{ matrix.torch}} -f https://download.pytorch.org/whl/cpu/torch_stable.html

          pip install k2==1.24.4.dev20240223+cpu.torch${{ matrix.torch }} -f https://k2-fsa.github.io/k2/cpu.html

          pip install kaldifeat==1.25.4.dev20240223+cpu.torch${{ matrix.torch }} -f https://csukuangfj.github.io/kaldifeat/cpu.html

          python3 setup.py bdist_wheel

          mkdir -p wheelhouse

          cp -v dist/* wheelhouse

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

      - name: Upload Wheel
        uses: actions/upload-artifact@v2
        with:
          name: torch-${{ matrix.torch }}-python-${{ matrix.python-version }}-macos-latest-cpu
          path: wheelhouse/*.whl

      # https://huggingface.co/docs/hub/spaces-github-actions
      - name: Publish to huggingface
        if: github.repository_owner == 'csukuangfj' || github.repository_owner == 'k2-fsa'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_LFS_SKIP_SMUDGE=1

            git clone https://huggingface.co/csukuangfj/sherpa huggingface
            cd huggingface
            git pull

            mkdir -p macos
            cp -v ../wheelhouse/*.whl ./macos
            git status
            git lfs track "*.whl"
            git add .
            git commit -m "upload macos wheel for torch ${{ matrix.torch }} python ${{ matrix.python-version }}"
            git push https://csukuangfj:$HF_TOKEN@huggingface.co/csukuangfj/sherpa main
