name: Publish to PyPI

on:
  push:
    tags:
      - '*'
    paths:
      - '.github/workflows/publish_to_pypi.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'sherpa/csrc/**'
      - 'sherpa/cpp_api/**'
      - 'sherpa/python/**'
  workflow_dispatch:

concurrency:
  group: pypi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel twine setuptools

      - name: Build
        shell: bash
        run: |
          python3 setup.py sdist
          ls -l dist/*

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/k2-sherpa-*.tar.gz
